# Generated by Django 5.0.3 on 2024-06-05 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_founded', models.PositiveIntegerField()),
                ('flights_outside_europe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('V', 'VIP')], max_length=1)),
                ('manufacturer', models.CharField(max_length=50)),
                ('max_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('total_flight_hours', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('airport_to', models.CharField(max_length=50)),
                ('airport_from', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonProject.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonProject.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonProject.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='AirlinePilots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonProject.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotAirBalloonProject.pilot')),
            ],
        ),
    ]
