# Generated by Django 5.0.3 on 2024-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotAirBalloonProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
