apiVersion: v1
kind: ConfigMap
metadata:
  name: balloon-config-map
  namespace: cicd-project
data:
  POSTGRES_HOST: postgres-database-svc.cicd-project.svc.cluster.local
  POSTGRES_NAME: balloon

---
apiVersion: v1
kind: Secret
metadata:
  name: balloon-secrets
  namespace: cicd-project
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balloon-app
  namespace: cicd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balloon-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: balloon-app
    spec:
      containers:
        - name: application
          image: stanchevskid/balloons-project:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: balloon-config-map
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: balloon-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: balloon-secrets
                  key: POSTGRES_PASSWORD
